import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SmoothScroller from "@/utils/SmoothScroller";
import Navbar from "@/reuseables/Navbar";
import Footer from "@/reuseables/Footer";

const aeonik = localFont({
  src: [
    {
      path: '../utils/fonts/AeonikTRIAL-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../utils/fonts/AeonikTRIAL-LightItalic.otf',
      weight: '300',
      style: 'italic',
    },
    {
      path: '../utils/fonts/AeonikTRIAL-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../utils/fonts/AeonikTRIAL-RegularItalic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../utils/fonts/AeonikTRIAL-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../utils/fonts/AeonikTRIAL-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
  ],
  variable: '--font-aeonik',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${aeonik.variable} ${aeonik.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScroller>
          <Navbar />
          {children}
          <Footer />
        </SmoothScroller>
      </body>
    </html>
  );
}
